# Generated by Django 5.0.4 on 2024-08-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonEntre",
            fields=[
                (
                    "code_bon_entre",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date_entre", models.DateField(blank=True, null=True)),
                ("quantite_entre", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BonSortie",
            fields=[
                (
                    "code_bon_sortie",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date_sortie", models.DateField(blank=True, null=True)),
                ("quantite_sortie", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmationEntre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_bon_entre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.bonentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmationSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_bon_sortie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.bonsortie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "code_fournisseur",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nom_fournisseur", models.CharField(max_length=50)),
                ("prenom_fournisseur", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "numero_telephone",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("adresse", models.CharField(max_length=100)),
                ("pays", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Gestionnaire",
            fields=[
                (
                    "code_gestionnaire",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nom_gestionnaire", models.CharField(max_length=50)),
                ("prenom_gestionnaire", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("numero_telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "code_inventaire",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date_inventaire", models.DateField(blank=True, null=True)),
                ("res", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "code_local",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("adresse_local", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "code_produit",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("designation", models.CharField(max_length=100)),
                ("date_fabrication", models.DateField(blank=True, null=True)),
                ("unite", models.CharField(blank=True, max_length=50, null=True)),
                ("quantite_stock", models.IntegerField()),
                ("quantite_util", models.IntegerField()),
                ("quantite_vandale", models.IntegerField()),
                (
                    "code_fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduitLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.local"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.produit",
                    ),
                ),
            ],
            options={
                "unique_together": {("produit", "local")},
            },
        ),
        migrations.DeleteModel(
            name="Produts",
        ),
        migrations.AddField(
            model_name="confirmationsortie",
            name="code_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.fournisseur"
            ),
        ),
        migrations.AddField(
            model_name="confirmationentre",
            name="code_fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.fournisseur"
            ),
        ),
        migrations.AddField(
            model_name="gestionnaire",
            name="code_local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.local",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="confirmationsortie",
            unique_together={("code_fournisseur", "code_bon_sortie")},
        ),
        migrations.AlterUniqueTogether(
            name="confirmationentre",
            unique_together={("code_fournisseur", "code_bon_entre")},
        ),
    ]
