# Generated by Django 5.0.4 on 2024-08-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0002_bonentre_bonsortie_confirmationentre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonentre",
            name="code_produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.produit",
            ),
        ),
        migrations.AddField(
            model_name="bonsortie",
            name="code_produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.produit",
            ),
        ),
    ]
