# Generated by Django 5.0.4 on 2024-08-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0004_remove_bonentre_code_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bonsortie",
            name="code_produit",
        ),
        migrations.AddField(
            model_name="produit",
            name="code_bon_entre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.bonentre",
            ),
        ),
    ]
