# Generated by Django 5.0.4 on 2024-08-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0005_remove_bonsortie_code_produit_produit_code_bon_entre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="code_bon_entre",
        ),
        migrations.AddField(
            model_name="bonentre",
            name="code_produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.produit",
            ),
        ),
        migrations.AddField(
            model_name="bonsortie",
            name="code_produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.produit",
            ),
        ),
    ]
